displayName: Simple Cache No Cache
summary: Simple cache plugin middleware caches responses on disk.
type: middleware
import: github.com/AnzeBlaBla/testctfthingy
compatibility: TODO
testData:
  path: /tmp
